[package]
name = "swiss"
version = "0.1.0"
edition = "2021"

[dependencies]
shellexpand = "3.1.0"
anyhow = "1.0"
structopt = "0.3.26"
rayon = "1.10.0"
chrono = "0.4.38"
rocket = "0.5.1"

[dependencies.rocket_dyn_templates]
version = "0.2.0"
features = ["handlebars", "tera", "minijinja"]
